spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true

springdoc:
  swagger-ui:
    path: swagger-ui

security:
  token-ttl: 14d
  secret: ${SEC_SECRET}